# Backend untuk terhubung ke Netlify (dari Langkah 4)
backend:
  name: git-gateway
  branch: main # PASTIKAN INI BENAR (branch utama Anda)

# Lokasi upload media (jika Anda mau upload gambar via CMS)
media_folder: "img" 
public_folder: "/img"

# Ini adalah "koleksi" data Anda (Form Anda)
collections:
  - name: "artikel" # ID internal
    label: "Artikel Blog" # Nama yang tampil di UI
    description: "Tambah atau edit artikel di sini"
    
    # Memberi tahu CMS untuk mengedit satu file ini:
    format: "json"
    file: "articles.json" 
    
    # Ini adalah field/kolom di form Anda
    # (Sesuai permintaan: Judul, Deskripsi, Content, Date, URL, Category)
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Konten", name: "content", widget: "markdown" }
      - { label: "Tanggal (Contoh: 25/10/2025)", name: "date", widget: "string" }
      - { label: "URL YouTube (Opsional)", name: "youtubeUrl", widget: "string", required: false }
      - { label: "Kategori", name: "categories", widget: "list" }
      